# Changes here will be overwritten by Copier
_commit: v2.2.0
_src_path: gh://lincc-frameworks/python-project-template
author_email: lincc-frameworks-team@lists.lsst.org
author_name: LINCC Frameworks
create_example_module: false
custom_install: custom
enforce_style:
- pylint
- black
- isort
failure_notification: []
include_benchmarks: false
include_docs: false
mypy_type_checking: none
package_name: pre_commit_hooks
project_description: Pre-Commit Hooks for LINCC Frameworks Python Project Template
project_license: BSD
project_name: template-version-check
project_organization: lincc-frameworks
python_versions:
- '3.9'
- '3.10'
- '3.11'
- '3.12'
- '3.13'
- '3.14'
test_lowest_version: none
