# Changes here will be overwritten by Copier
_commit: v1.3.0
_src_path: gh://lincc-frameworks/python-project-template
author_email: lincc-frameworks-team@lists.lsst.org
author_name: LINCC Frameworks
create_example_module: true
custom_install: true
include_notebooks: false
module_name: check_template_version
mypy_type_checking: none
preferred_linter: black
project_license: BSD
project_name: template-version-check
use_gitlfs: none
use_isort: true
