-   id: check-lincc-frameworks-template-version
    name: Check LINCC Frameworks template version
    description: Compares local template version to latest available version.
    entry: check-lincc-frameworks-template-version
    language: python
    always_run: true
